name: "pull-request"
on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - bugfix/*
  pull_request:
    types: [opened, reopened]

jobs:
  validation:
    name: Validation Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm install
      - name: Run test
        run: npm test

