name: "pull-request"
on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - bugfix/*
  pull_request:
    types: [opened, reopened]

jobs:
  validation:
    name: Validation Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Run test
        run: npm run test

